name: Branch Rules

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - recette
      - main
  workflow_dispatch: # Déclenchement manuel si nécessaire

permissions:
  contents: write  # Donne la permission d'écrire dans le dépôt pour le rebase

jobs:
  branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Display branch info
        run: |
          echo "Branch: ${{ github.ref }}"

      - name: Develop branch actions
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "Develop branch - Build & Push artefact to staging"

      - name: Recette branch actions
        if: github.ref == 'refs/heads/recette'
        run: |
          echo "Recette branch - Run qualimetry checks"

      - name: Main branch actions
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Main branch - Release artefact with SemVer"
