name: Build web game

on:
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: [ "CodeQL Analysis" ]  # Le nom du workflow CodeQL que tu veux exécuter en premier
    types:
      - completed

env:
  AZURE_WEBAPP_NAME: 'globomantics-web-game'   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '9.0'           

jobs:
  build:
    runs-on: ubuntu-latest
    needs: analyze

    steps:
      - uses: actions/checkout@main
      
      - name: 'Setup .NET Core'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      - name: 'Build app package'
        run: |
          dotnet restore '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/src/web-game/Globomantics.sln'
          dotnet build '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/src/web-game/Globomantics.sln' --configuration Release
          dotnet publish '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/src/web-game/Globomantics.sln' -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/app-package'