name: Deploy web game

on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: 'globomantics-web-game'   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '9.0'           

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@main
      
      - name: 'Release artefact with SemVer'
        run: |
          echo "Release artefact with SemVer"
